version: '3'

tasks:
  tidy:
    desc: Run go mod tidy.
    cmds:
      - go mod tidy

  fmt:
    desc: Run go fmt against code.
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet against code.
    cmds:
      - go vet ./...


  build:
    desc: Build manager binary.
    cmds:
      - task: fmt
      - task: vet
      - go build -o bin/manager main.go

  run:
    desc: Run a controller from your host.
    cmds:
      - task: fmt
      - task: vet
      - go run ./main.go --aws-region={{.AWS_REGION | default "eu-west-1"}} --cluster-name={{.CLUSTER_NAME | default "my-cluster"}}

  docker-build:
    desc: Build docker image with the manager.
    cmds:
      - docker build -t {{.IMG | default "pia-operator:latest"}} .

  docker-push:
    desc: Push docker image with the manager.
    cmds:
      - docker push {{.IMG | default "pia-operator:latest"}}

  install:
    desc: Install manifests into the K8s cluster specified in ~/.kube/config.
    cmds:
      - kubectl apply -f config/

  uninstall:
    desc: Uninstall manifests from the K8s cluster specified in ~/.kube/config.
    cmds:
      - kubectl delete -f config/ --ignore-not-found={{.IGNORE_NOT_FOUND | default "false"}}

  deploy:
    desc: Deploy controller to the K8s cluster specified in ~/.kube/config.
    cmds:
      - cd config/manager && kustomize edit set image controller={{.IMG | default "pia-operator:latest"}}
      - kubectl apply -k config/default

  undeploy:
    desc: Undeploy controller from the K8s cluster specified in ~/.kube/config.
    cmds:
      - kubectl delete -k config/default --ignore-not-found={{.IGNORE_NOT_FOUND | default "false"}}

  deps:
    desc: Download dependencies
    cmds:
      - go mod tidy
      - go mod download
